### ISSUE TITLE
Add npm author

### ISSUE THREAD

**Issue by DenisCarriere** [dfuse-io/eosws-js#1]
Are you planning on re-using `eosws` as the npm module? or planning on name spacing it as `@dfuse/eosws`?

https://www.npmjs.com/package/eosws

Send me your `npm` usernames and I can add them as maintainers as an npm author.

**Comment by fproulx-eoscanada** [comment]
@DenisCarriere SVP add me for now https://www.npmjs.com/~fproulx-dfuse_io
I'm sure @maoueh will want it too.

Thanks.

**Comment by maoueh** [comment]
I did not get the final decision yet, but we will probably go with `@dfuse/eosws`.

You can add me for now to the current package, my NPN user name is `maoueh`

**Comment by DenisCarriere** [comment]
👍  `@dfuse/eosws` is pretty slick! I'd also go with that

**Comment by DenisCarriere** [comment]
@maoueh I've added you as a maintainer to `eosws` on npm.

**Comment by DenisCarriere** [comment]
@maoueh & @fproulx-eoscanada I've added you both as `npm` admins to the `eosws` repo

**Comment by maoueh** [comment]
Just to confirm that we will use `@dfuse/eosws` for publishing, will do the current release later today and update the readme.

**Comment by DenisCarriere** [comment]
@maoueh 👍 correct

I simply pushed a last update on `eosws` since I was depending on it for a different project, once `@dfuse/eosws` is release I'll switch to that.
