### ISSUE TITLE
Mishandling of connect followed by a send request

### ISSUE THREAD

**Issue by AlexCppns** [dfuse-io/eosws-js#15]
code snippet:
```
// Inside app-container.component => componentDidMount()
eosclient.connect()

...

// inside page => componentDidMount()
this.listener = eosclient.getTransactionLifecycle(this.props.match.params.id)

this.listener.onMessage((message: InboundMessage<{ lifecycle: TransactionLifecycle }>) => {
    if (message.type === InboundMessageType.TRANSACTION_LIFECYCLE) {
         this.setState({ lifecycle: message.data.lifecycle })
    }
})
```

and I get the following error:

`Unhandled Rejection (InvalidStateError): Failed to execute ‘send’ on ‘WebSocket’: Still in CONNECTING state.`

**Comment by maoueh** [comment]
See https://github.com/dfuse-io/eosws-js/tree/stress-testing

**Comment by maoueh** [comment]
Ok, problem is usage of multiple calls to `connect` which is not handled correctly. To solve:
* In connect, if a connectionPromise already exists, returns it right away
* In connect, we need to handle reconnection flow, this is more tricky I think, will need to investigate further.
