### ISSUE TITLE
Throw exceptions when the websocket dies.

### ISSUE THREAD

**Issue by raphaelgodro** [dfuse-io/eosws-js#2]
From my testing 24/24 in the last week with this client implementation, I ran through an issue:

My websocket process was still running, however I was not getting any information from the chain more.  There should be a catch mechanism when the flow of data stops.

**Comment by maoueh** [comment]
The socket now re-connects automatically be default (configurable via socket option `autoReconnect`).

The `onClose` and `onError` options on the socket can be used to detected closing/error of the connection.

I'm not convinced we should add first-class support for message not flowing anymore. Will think about it.

However, will add related issues around reconnection (max retry, error on unable to reconnect) and error throwing when required.

**Comment by maoueh** [comment]
@raphaelgodro New development happens on https://github.com/dfuse-io/client-js/, hopefully, the reported error is now fixed on the new client (some work was made to have a keep alive to ensure TCP connection is closed even if only half of the connection is non-working).

New discussion can happen on the new repository if needed.
