### ISSUE TITLE
README misleading

### ISSUE THREAD

**Issue by Velua** [dfuse-io/eosws-js#22]
The latest README suggests one can import `EoswsConnector` with a 
    `npm install --save @dfuse/eosws-js`

However, from my tests I don't think `EoswsConnector` was introduced until version 0.12.0-beta.0 and npm installs `0.12.0` by default.

**Comment by maoueh** [comment]
Thanks for the report, we started working on the next version and this was an oversight.

I just reverted the `master` branch back to it's initial state (0.11.6 state) and created `next` branch to track progress of the next major bump.

Should be alright now. I tested both `yarn` (1.12.1) and `npm` (5.6.0) and they both install `0.11.6` by default. 

If it's not the case for you, I could investigate deeper. Closing.
